# This file was generated by GoReleaser. DO NOT EDIT.
cask "brtc" do
  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "224c66632dba2d4850f8d8a91cd33b7fb36511ffaa910bb929f32782293074c7"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "2b877023ee7dc3231ee3f869999975e09bb2965bdc577e8e6b5841558eee4f04"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "90378642e3fc934a512da54e3dd90e6e79a206f363a7c486e49c70b03b07794b"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "29692865c49867b0e091e7c8c65690a54add9e0d730155c7b582e7563908494d"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-amd64.tar.gz"
    end
  end

  name "brtc"
  desc "Cost calculator for offline password brute-force attacks"
  homepage "https://github.com/kanywst/brtc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brtc"

  # No zap stanza required
end
