# This file was generated by GoReleaser. DO NOT EDIT.
cask "brtc" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/brtc"]
    end
  end

  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "746eebed38671e7983a6274e7d7c9f965e9c829801c21040856363a732316549"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f838f6e9b6e0097daf167f4dcf77f9a3b80fbd01b9253b48b7ddd6232454f434"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73b53e4c179dfeed5cdb635e996bb51a733747333aed87df2a92c282b40831b0"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "b5a0799ac321c513625b903db3ade1989458a43711b10e3503b05ee5ace7abd5"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-amd64.tar.gz"
    end
  end

  name "brtc"
  desc "Cost calculator for offline password brute-force attacks"
  homepage "https://github.com/kanywst/brtc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brtc"

  # No zap stanza required
end
