# This file was generated by GoReleaser. DO NOT EDIT.
cask "brtc" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "d80d77750ab80c6ea28570805b413cc83f00530289a907171dd4f5df4f4691bf"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "b8f8437de2141f6cf0d33733de0f8a1bc429c4389940e88be1c9e49bcdc3d5c5"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "45431b0bfa1078fdf4da2ff4668c022879bba026952aee8105f180ad2533ec90"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "2bf8f7a22cbe818ff5fbda406e328293ae1e24d14c8283e6ad1754a5afa454fd"
      url "https://github.com/kanywst/brtc/releases/download/v#{version}/brtc-#{version}-linux-amd64.tar.gz"
    end
  end

  name "brtc"
  desc "Cost calculator for offline password brute-force attacks"
  homepage "https://github.com/kanywst/brtc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brtc"

  # No zap stanza required
end
