# This file was generated by GoReleaser. DO NOT EDIT.
cask "prpr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/prpr"]
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "bbff7727856e356fdde951969436d91fb57f5b433ffd49c964f5595b823e1b37"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "5ba2e45fdebd63370812787fb777bbfedba206a08d5f0ec7c1e2783a57456d03"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d8e1471eb787f2357342ae8b7714c9a065c6f91c350164b4b2bb345349c1a84"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "0370d3b15f829b85bc82f4e76b3992f78131f375daab2bf059b112603764f870"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-amd64.tar.gz"
    end
  end

  name "prpr"
  desc "Terminal dashboard for the open GitHub pull requests you can see"
  homepage "https://github.com/kanywst/prpr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prpr"

  # No zap stanza required
end
