# This file was generated by GoReleaser. DO NOT EDIT.
cask "prpr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/prpr"]
    end
  end

  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "97ac811530437561f5f9299dca99e8b3080cccde3e8a15937c7d6c020deb72aa"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "40714f0e1afe379210fdd9420fce97a03ec0fc77ebcbb66245bc903bbc2e27b9"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fbc397214ab44e08f6914b0242edc3744152f52d3541cc99e43cadd30b354c66"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "63797f86f95da2955449ae30220ff12f1b70fb44ccdbedf5819826ace8d58830"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-amd64.tar.gz"
    end
  end

  name "prpr"
  desc "Terminal dashboard for the open GitHub pull requests you can see"
  homepage "https://github.com/kanywst/prpr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prpr"

  # No zap stanza required
end
