# This file was generated by GoReleaser. DO NOT EDIT.
cask "prpr" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a62945736cc5f26619ef3ef12a01369da1533c6e4da40a66fbe6d29a34d7dcfb"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "8f733e1c77db5dd96da5f553ef12813f6bcb666199cef00f53260be6ba175785"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2454150b25afb9e45917af9d2a98cec09597b49cdc706c2f4f95a7f31bdc7595"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "7b0d0f96986291d507205843e5de3e2e7935f0f495b946be840676ff4a90227d"
      url "https://github.com/kanywst/prpr/releases/download/v#{version}/prpr-#{version}-linux-amd64.tar.gz"
    end
  end

  name "prpr"
  desc "Terminal dashboard for the open GitHub pull requests you can see"
  homepage "https://github.com/kanywst/prpr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prpr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prpr"]
    end
  end

  # No zap stanza required
end
