# This file was generated by GoReleaser. DO NOT EDIT.
cask "rapg" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "3d8b28ea67e598aa5d2231ded57666b0a9dc64ec27e4fae8ad48532a55b44847"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ac206d50a0455ef74ca2f98eb2ef18c58c80c5c159eff8751ce6b1f387e2671"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b2b80ac410eee7326a974a97541e122b8b3f1d88d7e98e3125af83be31f077b6"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f239edd5bad195449ff329cf2bea63493a95f161165aa73bc74b46b47e72e452"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_x86_64.tar.gz"
    end
  end

  name "rapg"
  desc "Local-first secret manager for the AI-agent era"
  homepage "https://github.com/kanywst/rapg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rapg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rapg"]
    end
  end

  # No zap stanza required
end
