# This file was generated by GoReleaser. DO NOT EDIT.
cask "rapg" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "09151f8c28cbdc838b5412d454fe27ce99943e181733d265c53480089750066b"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "95d841bcb82ef4b9240e1c21d0b8f5c8695d7f854ca64ffafa499deb3980f9ee"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "11b78a5f22048066a0fb8794874c30beb8092443fae5014db99ad27976a36ed9"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "637239d2ae35416de1b0d31c308190272efce51894fd666310ae3d589f83bbba"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_arm64.tar.gz"
    end
  end

  name "rapg"
  desc "Local-first secret manager for the AI-agent era"
  homepage "https://github.com/kanywst/rapg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rapg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rapg"]
    end
  end

  # No zap stanza required

end
