# This file was generated by GoReleaser. DO NOT EDIT.
cask "rapg" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "a55004c2d4593f09bcda31fe0fad424f3462b6e299dad6fc823778443b7f85c7"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5b87d8d415fb4cb5ca4db912289c2e8acb7280ee7b763bb03a2c0c7c0eb2d809"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ffed72280b078489fbaa9941138d2a5d5ae8e05beb5ddff0f78681c4acc9d68"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d7ef157948f1a5b98c92d7796fa2bf554ae21b502aae5cea6e18385b9142a32d"
      url "https://github.com/kanywst/rapg/releases/download/v#{version}/rapg_Linux_arm64.tar.gz"
    end
  end

  name "rapg"
  desc "Local-first secret manager for the AI-agent era"
  homepage "https://github.com/kanywst/rapg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rapg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rapg"]
    end
  end

  # No zap stanza required

end
