# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  version "0.8.2"

  on_macos do
    on_intel do
      sha256 "5f7c54ee50ae0f24fd77584925ae3941fc3a21cc8bfa2a8e763ae40b2eb0c4df"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5ead7d8cc1ce2719c795803db49adae77b7d3438f2e1ff6ee8108b82b0abf07b"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c411786d2b1f87d9da9342968ec3eac22ce5f0d9167be9e307d99eea877f0bf8"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "aa6ded82935b9a6f0705d335935fa796f274752ca6eed0c7b91027e577430bdc"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
    end
  end

  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  zsh_completion "completions/y509.zsh"

  # No zap stanza required

end
