# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "9836548c68ebc12b09b38432b075feb034d26a68cc2aab8c41ce125c6d65feba"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "cdb6c2650a1b7ef61b9c8421037e1c0e9bfad973211330cb2cd5e7cdc194c5cd"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "718a421ae382fabc337d20b45e76bab7abcee41c37bb00dcd726afceb04df610"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "e9a550d0806ab011de1f6be36f530fc556fd3e371483b8e3eda3346e05785c63"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
    end
  end

  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  zsh_completion "completions/y509.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/y509"]
    end
  end

  # No zap stanza required
end
