# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/y509"]
    end
  end

  version "1.8.0"

  on_macos do
    on_arm do
      sha256 "ebc874845a6eb5e9488de81bf19319b669e59bb9927f9ca72e3677ae133faf74"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "1549a3baaed75dc2e3e7bde76a6959e7b2fb3ca3a9b17360d2af2ea5fa097470"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "45267fa2b60ea0bf4023beb31d30da258321341eb377d5bdd4e9b15725958c41"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "558682e16a7a02d3160eef7fdc224c36d29a77d79d8d03b3d0ce291c00e3df1c"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
    end
  end

  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  fish_completion "completions/y509.fish"
  zsh_completion "completions/y509.zsh"

  # No zap stanza required
end
