# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpOpaAuthz < Formula
  desc "Answer agent authorization questions with OPA Rego or an AuthZEN PDP"
  homepage "https://github.com/kanywst/mcp-opa-authz"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.1/mcp-opa-authz-0.3.1-darwin-amd64.tar.gz"
      sha256 "cf175deec745c13fbbddd26e521250b3254d28d7d06d91c915262b153514225c"

      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.1/mcp-opa-authz-0.3.1-darwin-arm64.tar.gz"
      sha256 "29e648a5abacc7e3ba451460467fcbaac92bfbd7ee9422668b5770a928c9a05c"

      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.1/mcp-opa-authz-0.3.1-linux-amd64.tar.gz"
      sha256 "ce2a816dfaf56e6c85c866e39a7217a1fced2c304af18d876db4af8ab72dd197"
      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.1/mcp-opa-authz-0.3.1-linux-arm64.tar.gz"
      sha256 "9fd35f40a4aeee0db29ceeb670561170f1fa02037b4f6ae3dab006d1be251071"
      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
  end

  test do
    system "#{bin}/mcp-opa-authz", "--version"
  end
end
