# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpOpaAuthz < Formula
  desc "Answer agent authorization questions with OPA Rego or an AuthZEN PDP"
  homepage "https://github.com/kanywst/mcp-opa-authz"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.0/mcp-opa-authz-0.3.0-darwin-amd64.tar.gz"
      sha256 "5b3d640d58acbf538a8f286beed4cc037bb1842619641279f3fa92303a02f731"

      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.0/mcp-opa-authz-0.3.0-darwin-arm64.tar.gz"
      sha256 "1da56b920fff84b442c809b065c245fb30e58927157c6304b54312ed51b33df9"

      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.0/mcp-opa-authz-0.3.0-linux-amd64.tar.gz"
      sha256 "c470d67516e7007c779481a14292ee50af5e412838169e7ec4192e56e8d1e37b"
      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/mcp-opa-authz/releases/download/v0.3.0/mcp-opa-authz-0.3.0-linux-arm64.tar.gz"
      sha256 "db41eadba5900fca6d62da55992cc4fe483ba4c23c42f26912f6fba0b5b1193d"
      define_method(:install) do
        bin.install "mcp-opa-authz"
      end
    end
  end

  test do
    system "#{bin}/mcp-opa-authz", "--version"
  end
end
