# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rapg < Formula
  desc "The Developer-First Secret Manager."
  homepage "https://github.com/kanywst/rapg"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.1/rapg_Darwin_x86_64.tar.gz"
      sha256 "901c1f059159f7bccbcd00b1f233769b9829e9b01a2acb19e90bddafa7bae979"

      define_method(:install) do
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.1/rapg_Darwin_arm64.tar.gz"
      sha256 "6aeb5ff95d6af384f8fffe832cb8e9a13f93a843d9522c4c36be830a0a2f0470"

      define_method(:install) do
        bin.install "rapg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.1/rapg_Linux_x86_64.tar.gz"
      sha256 "04748804b966f8fe98a97383151016803a46434a0556393f3d6be9682cab06f3"
      define_method(:install) do
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.1/rapg_Linux_arm64.tar.gz"
      sha256 "66394a433b8e0865dd3f6ae062f53735e8b6d98777d47a3794a282058f90dcd9"
      define_method(:install) do
        bin.install "rapg"
      end
    end
  end

  test do
    system "#{bin}/rapg gen --help"
  end
end
