# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rapg < Formula
  desc "The Developer-First Secret Manager."
  homepage "https://github.com/kanywst/rapg"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.0/rapg_Darwin_x86_64.tar.gz"
      sha256 "377b858d9eea6d4a2739e1263629cbd0ed770de906e20d1b55569305b02847a0"

      def install
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.0/rapg_Darwin_arm64.tar.gz"
      sha256 "18c200a666b500b0a875df7ac13e1571831fac97fbc9fa41b7ae25d3f966bbac"

      def install
        bin.install "rapg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.0/rapg_Linux_x86_64.tar.gz"
      sha256 "5bf1f2d9e2c838c9e01f6c38473c6c963165ff8f3e6c47fa1f04454210858e49"

      def install
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.0/rapg_Linux_arm64.tar.gz"
      sha256 "f1e85c7f59b1506bcb36560f8943c8b1f404f6d04d58c8668c5c6939d66abaed"

      def install
        bin.install "rapg"
      end
    end
  end

  test do
    system "#{bin}/rapg", "gen", "--help"
  end
end
