# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rapg < Formula
  desc "The Developer-First Secret Manager."
  homepage "https://github.com/kanywst/rapg"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.2/rapg_Darwin_x86_64.tar.gz"
      sha256 "124f29004efdca9eec3b0c81485ec501ff0b228806a52508b7b6b736be68afc9"

      define_method(:install) do
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.2/rapg_Darwin_arm64.tar.gz"
      sha256 "ac7ca2fcefb7f507acea49b5010dcfad7b1ff4efee3946b315de415850049d26"

      define_method(:install) do
        bin.install "rapg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.2/rapg_Linux_x86_64.tar.gz"
      sha256 "20289bfede687b9bdde3623bdb8d32b678614e3dc6abc4139de6d08ac7ed6cdc"
      define_method(:install) do
        bin.install "rapg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/rapg/releases/download/v0.3.2/rapg_Linux_arm64.tar.gz"
      sha256 "91e47079f6e67061e6d3a37d3a34b34efe55f9b512c88bdee7badc160b63d5ec"
      define_method(:install) do
        bin.install "rapg"
      end
    end
  end

  test do
    system "#{bin}/rapg gen --help"
  end
end
