# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpiffeComplianceChecker < Formula
  desc "Static MUST-clause compliance checker for SPIFFE artifacts (SPIFFE-ID, X.509-SVID, JWT-SVID, Trust Bundle)."
  homepage "https://github.com/kanywst/spiffe-compliance-checker"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.1.0/spiffe-compliance-checker_0.1.0_darwin_amd64.tar.gz"
      sha256 "383f8346eccee79f4f42440205367bb073deaff65822288ed324f39cd5a7384a"

      define_method(:install) do
        bin.install "scc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.1.0/spiffe-compliance-checker_0.1.0_darwin_arm64.tar.gz"
      sha256 "499b6747a073158a9a01b18341cfae1e99197dcb3355e51c8df0bfb14f322748"

      define_method(:install) do
        bin.install "scc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.1.0/spiffe-compliance-checker_0.1.0_linux_amd64.tar.gz"
      sha256 "1bca3995c297b690b7a49431eb2e3a08a798f83587a2c05e5e230b53a2b0d0c3"
      define_method(:install) do
        bin.install "scc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.1.0/spiffe-compliance-checker_0.1.0_linux_arm64.tar.gz"
      sha256 "bff84d238145d7aa4f7a97ef882b4deb51d5c0a2ab3a8775dcd84e515183f8d5"
      define_method(:install) do
        bin.install "scc"
      end
    end
  end

  test do
    system "#{bin}/scc", "--version"
  end
end
