# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpiffeComplianceChecker < Formula
  desc "Static MUST-clause compliance checker for SPIFFE artifacts"
  homepage "https://github.com/kanywst/spiffe-compliance-checker"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.5.0/spiffe-compliance-checker_0.5.0_darwin_amd64.tar.gz"
      sha256 "f275a6f1f96cbb8aaa2db42cd055289288499c37e992390053da3c9b099c91ab"

      define_method(:install) do
        bin.install "scc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.5.0/spiffe-compliance-checker_0.5.0_darwin_arm64.tar.gz"
      sha256 "df4db69a247df9c0a15ea67f9ebe3964d467c0b9cb141aa9c9d073404c7dd28a"

      define_method(:install) do
        bin.install "scc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.5.0/spiffe-compliance-checker_0.5.0_linux_amd64.tar.gz"
      sha256 "82f344245a124852cf7907a0029b05e65466050857bafa28034768e166cbca65"
      define_method(:install) do
        bin.install "scc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanywst/spiffe-compliance-checker/releases/download/v0.5.0/spiffe-compliance-checker_0.5.0_linux_arm64.tar.gz"
      sha256 "fd5a469e801c62798e5f910862c21aec4e338f06983fcf7cd5ab0f2062b5c62d"
      define_method(:install) do
        bin.install "scc"
      end
    end
  end

  test do
    system "#{bin}/scc", "--version"
  end
end
