# typed: false
# frozen_string_literal: true

# This file was generated by kanywst/wimsey .github/workflows/release.yml. DO NOT EDIT.
class Wimsey < Formula
  desc "Issue, verify and inspect WIMSE workload identity credentials"
  homepage "https://github.com/kanywst/wimsey"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.6.3/wimsey-v0.6.3-aarch64-apple-darwin.tar.gz"
      sha256 "f874c1f604d567e376a1e7ce505d4c8a5d8361f53168eb79144d4245543f798a"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.6.3/wimsey-v0.6.3-x86_64-apple-darwin.tar.gz"
      sha256 "017f42c9c0b372b76f91fbd916a62fa005736def0ede53a5f96dafc1fecc22c9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.6.3/wimsey-v0.6.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2cb97f88637b64129c69aa477aac36a4f3bd39bafac9fb272fb094a121f26b99"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.6.3/wimsey-v0.6.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a5600ee59db4f3512c5490d15ed5c0d9914926a954a1f2c1977915b926c61e95"
    end
  end

  def install
    bin.install "wimsey"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wimsey --version")
  end
end
