# typed: false
# frozen_string_literal: true

# This file was generated by kanywst/wimsey .github/workflows/release.yml. DO NOT EDIT.
class Wimsey < Formula
  desc "Issue, verify and inspect WIMSE workload identity credentials"
  homepage "https://github.com/kanywst/wimsey"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.7.0/wimsey-v0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "e168d971a4dd01a58d485ddef0e339d920729d2135e21383066c3189a1b2d500"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.7.0/wimsey-v0.7.0-x86_64-apple-darwin.tar.gz"
      sha256 "2526dd1418f800c2b62a2c745ecc15d6ba8e8b2fe053e5eb1548d67a005ad0b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.7.0/wimsey-v0.7.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "687bd6968944b8d3556c97a0c3899240b68a2f035b6828ca249f7e94508a9ad1"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.7.0/wimsey-v0.7.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1e24f1f08ddac727b35aa441f23c34d345e22d95a08f311092768963cb59a7bf"
    end
  end

  def install
    bin.install "wimsey"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wimsey --version")
  end
end
