# typed: false
# frozen_string_literal: true

# This file was generated by kanywst/wimsey .github/workflows/release.yml. DO NOT EDIT.
class Wimsey < Formula
  desc "Issue, verify and inspect WIMSE workload identity credentials"
  homepage "https://github.com/kanywst/wimsey"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.8.0/wimsey-v0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "64d095502582303148b11ede890534b803d1a10698cf67f63ea7c1646f9c5366"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.8.0/wimsey-v0.8.0-x86_64-apple-darwin.tar.gz"
      sha256 "fca084ba6b1e378991b22f77a4e8356c75bd64d2d9ce8f08e30b181a88b4eb38"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kanywst/wimsey/releases/download/v0.8.0/wimsey-v0.8.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2186cec5bdbb4dfc191979a6787524beff953e7468875d317961ad0a3939d335"
    end
    on_intel do
      url "https://github.com/kanywst/wimsey/releases/download/v0.8.0/wimsey-v0.8.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "383346707f91dcea16b819843ba7e512c8ac01108ff4cde980283271d6101a77"
    end
  end

  def install
    bin.install "wimsey"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wimsey --version")
  end
end
